### ISSUE TITLE
Wrong value

### ISSUE THREAD

**Issue by syrhus** [syrhus/solax_inverter#5]
I installed the plugin in my domoticz, but the strange thing is that it gives me the wrong data:
When i look into my devices i see the correct data:
![image](https://user-images.githubusercontent.com/35039914/115952099-8d984f00-a4e4-11eb-9aa6-e83c4ecdabd1.png)
Here it says that the proceeds sofar is 2500 Watts
But when i look in the Utils i see different values:
![image](https://user-images.githubusercontent.com/35039914/115952199-f089e600-a4e4-11eb-8c08-d79261727411.png)
Here i see the value that it (SOLAX - 1) produces now (916 Watts) and a total of -17900 Watts.
Is it possible that the totals for today and total all are produced here?

_Originally posted by @Rudi1952 in https://github.com/syrhus/solax_inverter/issues/4#issuecomment-826055430_

**Comment by syrhus** [comment]
Hi Rudi1952

I do not have any idea of the -17.9KWh . Your current value, 916, seems to be good.
Do you have 1 inverter only? or 2?
Could you please try to enter the following URL in another web :

https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=**YOUR_TOKEN_ID**&sn=**YOUR_SERIAL_NUMBER**

what value do you have in "yieldtoday" field?

Regards

**Comment by Rudi1952** [comment]
I have only 1 inverter, it's a SOLAX X1 boost
The output of the URL is:
{"exception":"Query success!","result":{"inverterSN":"_my token_","sn":"_my serial number_","acpower":1386.0,"yieldtoday":5.6,"yieldtotal":36.8,"feedinpower":0.0,"feedinenergy":0.0,"consumeenergy":0.0,"feedinpowerM2":0.0,"soc":0.0,"peps1":0.0,"peps2":0.0,"peps3":0.0,"inverterType":"4","inverterStatus":"102","uploadTime":"2021-04-24 11:44:22","batPower":0.0,"powerdc1":913.0,"powerdc2":519.0},"success":true}

Strange thing is that it gives the right value for today when i look at my device, here it says that i used 5,6 kwh.
![image](https://user-images.githubusercontent.com/35039914/115954869-92b0ca80-a4f3-11eb-9e8d-31eeba0b98cd.png)

**Comment by Rudi1952** [comment]
Yesterday i removed the SOLAX hardware from domoticz and re-installed it again. At that moment all figures were back to zero.
This morning at 5.44 am, it started with a negative value of -21300 Wh. 
Yesterday i produced about that value. 
At 5.44 am it starts Solax (30 minutes before sunset.)
![image](https://user-images.githubusercontent.com/35039914/115985404-031b2280-a5ac-11eb-81dc-80c9e44c90d3.png)
Probably it picks the value from solaxcloud at that time?

**Comment by syrhus** [comment]
Hi,

I do not understand how you could have value during night as the plugin does not request value during night.
Have you tried to set the debug value to true to check if there is something wrong like the communication with Domoticz to get the sunset and sunrise time?

**Comment by Rudi1952** [comment]
It picks up negative data at 05.44 am, that is 30 minutes before sunrise. Time and date in domoticz and RPI are correct.

Sunrise in domoticz is at: 06.14
Sunset in domoticz is at: 20.50

When i look at the logfile (debug)it says:
2021-04-25 22:35:34.847  Solax: (Solax) sunrise:05:44:00
2021-04-25 22:35:34.847  Solax: (Solax) sunset:21:20:00
2021-04-25 22:36:03.016  Solax: (Solax) Pushing 'onHeartbeatCallback' on to queue
2021-04-25 22:36:03.066  (Solax) Processing 'onHeartbeatCallback' message
2021-04-25 22:36:03.066  Solax: (Solax) Calling message handler 'onHeartbeat'.
2021-04-25 22:36:03.066  Solax: (Solax) onHeartbeat called
2021-04-25 22:36:03.067  Solax: (Solax) now: 2021-04-25
2021-04-25 22:36:03.067  Solax: (Solax) currentDate:2021-04-25
2021-04-25 22:36:03.067  Status: Solax: (Solax) Off
2021-04-25 22:36:03.067  Solax: (Solax) Night time, no data to retrieve


I think this is correct, because in the hardware is filled:
Minutes avant/après le lever/coucher du soleil: 30
Heure d'été: 1

**Comment by syrhus** [comment]
Could you set the "Heure d'été"  (Summer Time) plugin parameter to 0 please and update?
Regards

**Comment by Rudi1952** [comment]
I updated the 'Summer Time' parameter to '0' and this solved the issue.
Many thanks for the support.
